---
title: "Applied Bayesian Analysis : NCSU ST 540"
subtitle: "Midterm2"
author: "Bruce Campbell"
fontsize: 11pt
output: pdf_document
bibliography: BruceCampbell_ST540_HW_1.bib
---

---
```{r setup, include=FALSE,echo=FALSE}
rm(list = ls())
setwd("d:/brucebcampbell-git/bayesian-learning-with-R")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev = 'pdf')
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(prompt=FALSE)
knitr::opts_chunk$set(fig.height=5)
knitr::opts_chunk$set(fig.width=6)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_knit$set(root.dir = ".")
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=38),tidy=TRUE)
library(latex2exp)   
library(pander)
library(ggplot2)
library(GGally)
```

```{r,echo=FALSE}
library(rjags)
library(coda)
library(modeest)
library(MASS)
load("E2.RData")
cov.y1  <- cov(Y1, use = "pairwise.complete.obs")
ggplot(data.frame(Y3=Y3) ,aes(x=1:365, y=Y3)) + geom_point(alpha=0.25) + geom_smooth( method="loess", span=0.22) +ggtitle("Y3")
ggplot(data.frame(mean.Y1=rowMeans(Y1,na.rm = TRUE)) ,aes(x=1:365, y=mean.Y1)) + geom_point(alpha=0.25) + geom_smooth( method="loess", span=0.22) +ggtitle("Row Means Y1")
N <- nrow(Y1)
p = 6
library(R2OpenBUGS)

openbugs_model <- function(){
  
  Y1pred[1,1:p] ~ dmnorm( Y1[1,1:p] ,precision[,])
  
  for(i in 2:N) {
    Y1pred[i,1:p] ~ dmnorm( theta[i,1:p] ,precision[,])
    
    #Y2[i] ~ dnorm(theta[i,1],sigmaY2) <-----Log said model is syntatically correct. CODAchain1.txt said "OpenBUGS did not run correctly." 
    
    theta[i,1]<-  mu2[1] + rho * Y1[i-1,1] #theta[i,1]<-  mu2[1] + rho * (Y1[i-1,1]+ Y2[i-1])/2 <--------DOESNT COMPILE
    theta[i,2]<-  mu2[2] + rho * Y1[i-1,2]
    theta[i,3]<-  mu2[3] + rho * Y1[i-1,3]
    theta[i,4]<-  mu2[4] + rho * Y1[i-1,4]
    theta[i,5]<-  mu2[5] + rho * Y1[i-1,5]
    theta[i,6]<-  mu2[6] + rho * Y1[i-1,6]

    #Y3[i] ~ dnorm(1/6*(Y1[i-1,1] +Y1[i-1,2]+ Y1[i-1,3]+ Y1[i-1,4] +Y1[i-1,5] +Y1[i-1,6]),sigmaY3) <- DOESNT COMPILE
    }
  
  # Priors
  rho  ~  dunif(0,1)
  sigmaY3 ~ dnorm(0, 0.01)
  sigmaY2  ~ dnorm(0, 0.01)
    
  for(j in 1:p)
  {
    mu2[j]  ~  dnorm(0,0.01)
  }
  
  precision[1:p,1:p] ~ dwish(R[,],k)
  
  SigmaVAR[1:p,1:p] <- inverse(precision[1:p,1:p])
  
  # Missing data model for x
  for(i in 1:N){
    Y1[i,1:p]~dmnorm(Y1_mn[],Y1_prec[,])
  }
  
  # Priors for missing-data model parameters
  for(j in 1:p){
    Y1_mn[j]~dnorm(0,0.01)
  }
  Y1_prec[1:p,1:p]~dwish(R[,],k)
  
  k <- p+0.1
  for(j1 in 1:p)
  {
    for(j2 in 1:p)
    {
      R[j1,j2] <- 0.1*equals(j1,j2)
    }
  }
}

n.chains = 2

stacks_dat <- list(Y1=scale(Y1),Y2=scale(Y2),Y3=scale(Y3), p = 6,   N = 365)
mlr_inits <- function() {   list( rho = 0.20) }
samps <- bugs(data = stacks_dat, 
            inits = mlr_inits, 
            parameters.to.save = c("Y1pred"), 
            model.file = openbugs_model, 
            codaPkg = TRUE,#,debug=TRUE,
            n.chains = n.chains, n.burnin=20000, n.iter = 40000, n.thin=10, DIC=F)

out.coda <- read.bugs(samps)

if(n.chains > 1)
{
  g <- matrix(NA, nrow=nvar(out.coda), ncol=2)
  for (v in 1:nvar(out.coda)) {
   g[v,] <- gelman.diag(out.coda[,v])$psrf
  }
  count.coeff.gt <- sum(g[,1]>1.1)
  count.coeff.gt
  plot(g[,1],main="Gelman-Rubin ")
}

chains.ess <- lapply(out.coda,effectiveSize)

first.chain.ess <- chains.ess[1]
plot(unlist(first.chain.ess), main="Effective Sample Size")

chain <- out.coda[[1]]
posterior.means <- list()
posterior.modes <- list()

for( i in 1:(365*6) )
{  
  colname <- colnames(chain)[i]
  print(colname)
  samples <- chain[,i]
  
  posterior.means[i] <-mean(samples)
  
  posterior.modes[i] <-mlv(samples)$M
}

theta.map <-  matrix(unlist(posterior.means)[1:2190],ncol=6, byrow=FALSE)

unscaled.theta.map <- ( theta.map +colMeans(Y1,na.rm = TRUE)) *  apply(Y1, 2,sd,na.rm = TRUE)

image(Y1, main="Y1")

image(unscaled.theta.map, main="Imputed")

plot(chain[,23])


plot(chain[,34])

#Sigma.map <-  matrix(unlist(posterior.means)[2191:2191+36],ncol=6, byrow=FALSE)
#heatmap(Sigma.map, main = "MAP Sigma")
#heatmap(cov.y1,main = "cov of Y1")
write.csv(unscaled.theta.map,file = "unscaled-theta-map.csv")
```
